### ISSUE TITLE
Clicking on field doesn't show curser

### ISSUE THREAD

**Issue by rptwsthi** [devikkim/ValidationTextField#1]
When I click on text field it doesn't show curser on page.

![Simulator Screen Shot - iPhone Xʀ - 2019-09-12 at 13 32 20](https://user-images.githubusercontent.com/1061288/64765521-de527280-d561-11e9-9bb8-2171f5af1e98.png)

**Comment by devikkim** [comment]
Please check your textfield’s tint color, and also i will check it in my
side.

**Comment by rptwsthi** [comment]
> Please check your textfield’s tint color, and also i will check it in my side.
> […](#)

This worked, tint was set to transparent by default. Changing that worked. :-)
